services:
  backend:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  satellite:
    build:
      context: ./satellite-services/envsat1
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://backend:8000/telemetry
    depends_on:
      - backend
    volumes:
      - ./satellite-services/envsat1:/app
